### PR TITLE
Width & height intrinsic values

### PR DESCRIPTION
**Pull request by erykpiast**

### CODE REVIEW

**Comment by erykpiast** [comment]
@giraud any feedback on this?

**Comment by giraud** [comment]
Hi,
I want to keep Width and Height to be in sync with the corresponding mdn pages.

**Comment by erykpiast** [comment]
Thank you for the comment! Do you mean you would prefer to keep separate modules instead of unified Size?

**Comment by giraud** [comment]
that's it

**Comment by erykpiast** [comment]
Hey @giraud! Sorry for the silence, I didn't have time to work on the changes you requested. Did these changes land somehow in v13? Or should I port them and create new PR? Or you don't consider them as valuable addition anymore?

**Comment by giraud** [comment]
@erykpiast I'm closing staled pr, but you can reopen it when you have new code

**Pull request closed without merging**
